name: Electron Build
on:
  push:
    branches:
      - 'electron/**'
jobs:
  build:
    runs-on: ${{matrix.os}}
    environment: 'development'
    env:
      REACT_APP_INFURA_URL: ${{secrets.INFURA_URL}}
      REACT_APP_FORTMATIC_API_KEY: ${{secrets.FORTMATIC_API_KEY}}
      REACT_APP_PORTIS_DAPP_ID: ${{secrets.PORTIS_DAPP_ID}}
      REACT_APP_INFURA_ID: ${{secrets.INFURA_ID}}
      REACT_APP_CLOUDINARY_PREFIX: ${{secrets.CLOUDINARY_PREFIX}}
      REACT_APP_CLOUDINARY_CLOUD_NAME: ${{secrets.CLOUDINARY_CLOUD_NAME}}
      REACT_APP_ETH_CHAIN: ${{secrets.ETH_CHAIN}}
      REACT_APP_VERSION: ${{secrets.APP_VERSION}}
      REACT_APP_ZERO_API_URL: ${{secrets.ZERO_API_URL}}
      REACT_APP_SENTRY_DSN: ${{secrets.SENTRY_DSN}}
      REACT_APP_WEB3_AUTHENTICATE_MESSAGE: ${{secrets.WEB3_AUTHENTICATE_MESSAGE}}
      REACT_APP_GIPHY_SDK_KEY: ${{secrets.GIPHY_SDK_KEY}}
      REACT_APP_MESSENGER_INVITE_PATH: ${{vars.MESSENGER_INVITE_PATH}}
      REACT_APP_ASSETS_PATH: ${{vars.ASSETS_PATH}}
      REACT_APP_ANDROID_STORE_PATH: ${{vars.ANDROID_STORE_PATH}}
      REACT_APP_MATRIX_HOME_SERVER_URL: ${{vars.MATRIX_HOME_SERVER_URL}}
      REACT_APP_ZNS_EXPLORER_URL: ${{vars.ZNS_EXPLORER_URL}}
    strategy:
      matrix:
        os: [macos-latest-xlarge]
        # os: [macos-latest, macos-latest-xlarge]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Get node version
        id: node
        shell: bash
        run: echo "version=$(node -v)" >> $GITHUB_OUTPUT
      - name: Get node_modules cache
        uses: actions/cache@v4
        id: node_modules
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}-${{ steps.node.outputs.version }}
      - run: echo '//npm.pkg.github.com/:_authToken=${{secrets.GITHUB_TOKEN}}' >> .npmrc
      - run: npm install
      - name: Add MacOS certs
        if: matrix.os == 'macos-latest' || matrix.os == 'macos-latest-xlarge'
        run: chmod +x ./scripts/add-macos-cert.sh && ./scripts/add-macos-cert.sh
        env:
          MACOS_CERT_P12: ${{ secrets.MACOS_CERT_P12 }}
          MACOS_CERT_PASSWORD: ${{ secrets.MACOS_CERT_PASSWORD }}
      - name: Publish app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
        run: npm run electron:publish
